name: Windows Build Testing 

env:
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e
  BUILD_REPOSITORY: https://github.com/eclipse/jkube.git 
  BUILD_REVISION: master
  BUILD_NAME: jkube

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: BuildWithoutTests
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        java: [17]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache .m2 registry
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: cache-e2e-${{ github.sha }}-${{ github.run_id }}
      - name: Clone 
        run: |
          git config --system core.longpaths true
          git clone $env:BUILD_REPOSITORY --branch $env:BUILD_REVISION $env:BUILD_NAME
      - name: Build 
        run: |
          cd $env:BUILD_NAME
          mvn clean install
